export type AttributeType = 
    | "generic.maxHealth"
    | "generic.followRange"
    | "generic.knockbackResistance"
    | "generic.movementSpeed"
    | "generic.attackDamage"
    | "generic.armor"
    | "generic.armorToughness"
    | "generic.attackKnockback"
    | "generic.attackSpeed"
    | "generic.luck"
    | "horse.jumpStrength"
    | "generic.flyingSpeed"
    | "zombie.spawnReinforcements"