export type BiomeId = 
    | 'ocean'                              /** 海洋 */
    | 'plains'                             /** 平原 */
    | 'desert'                             /** 沙漠 */
    | 'mountains'                          /** 山地 */ 
    | 'forest'                             /** 森林 */
    | 'taiga'                              /** 针叶林 */
    | 'swamp'                              /** 沼泽 */
    | 'river'                              /** 河流 */
    | 'nether_wastes'                      /** 下界荒地 */     
    | 'the_end'                            /** 末地 */
    | 'frozen_ocean'                       /** 冻洋 */     
    | 'frozen_river'                       /** 冻河 */     
    | 'snowy_tundra'                       /** 积雪的冻原 */     
    | 'snowy_mountains'                    /** 雪山 */     
    | 'mushroom_fields'                    /** 蘑菇岛 */     
    | 'mushroom_field_shore'               /** 蘑菇岛岸 */             
    | 'beach'                              /** 沙滩 */
    | 'desert_hills'                       /** 沙漠丘陵 */     
    | 'wooded_hills'                       /** 繁茂的丘陵 */     
    | 'taiga_hills'                        /** 针叶林丘陵 */ 
    | 'mountain_edge'                      /** 山地边缘 */     
    | 'jungle'                             /** 丛林 */
    | 'jungle_hills'                       /** 丛林丘陵 */     
    | 'jungle_edge'                        /** 丛林边缘 */ 
    | 'deep_ocean'                         /** 深海 */ 
    | 'stone_shore'                        /** 石岸 */ 
    | 'snowy_beach'                        /** 积雪的沙滩 */ 
    | 'birch_forest'                       /** 桦木森林 */     
    | 'birch_forest_hills'                 /** 桦木森林丘陵 */         
    | 'dark_forest'                        /** 黑森林 */ 
    | 'snowy_taiga'                        /** 积雪的针叶林 */ 
    | 'snowy_taiga_hills'                  /** 积雪的针叶林丘陵 */         
    | 'giant_tree_taiga'                   /** 巨型针叶林 */         
    | 'giant_tree_taiga_hills'             /** 巨型针叶林丘陵 */             
    | 'wooded_mountains'                   /** 繁茂的山地 */         
    | 'savanna'                            /** 热带草原 */
    | 'savanna_plateau'                    /** 热带高原 */     
    | 'badlands'                           /** 恶地 */ 
    | 'wooded_badlands_plateau'            /** 繁茂的恶地高原 */             
    | 'badlands_plateau'                   /** 恶地高原 */         
    | 'small_end_islands'                  /** 末地小型岛屿 */         
    | 'end_midlands'                       /** 末地中型岛屿 */     
    | 'end_highlands'                      /** 末地高岛 */     
    | 'end_barrens'                        /** 末地荒岛 */ 
    | 'warm_ocean'                         /** 暖水海洋 */ 
    | 'lukewarm_ocean'                     /** 温水海洋 */     
    | 'cold_ocean'                         /** 冷水海洋 */ 
    | 'deep_warm_ocean'                    /** 暖水深海 */     
    | 'deep_lukewarm_ocean'                /** 温水深海 */         
    | 'deep_cold_ocean'                    /** 冷水深海 */     
    | 'deep_frozen_ocean'                  /** 封冻深海 */         
    | 'the_void'                           /** 虚空 */ 
    | 'sunflower_plains'                   /** 向日葵平原 */         
    | 'desert_lakes'                       /** 沙漠湖泊 */     
    | 'gravelly_mountains'                 /** 沙砾山地 */         
    | 'flower_forest'                      /** 繁花森林 */     
    | 'taiga_mountains'                    /** 针叶林山地 */     
    | 'swamp_hills'                        /** 沼泽山丘 */ 
    | 'ice_spikes'                         /** 冰刺平原 */ 
    | 'modified_jungle'                    /** 丛林变种 */     
    | 'modified_jungle_edge'               /** 丛林边缘变种 */             
    | 'tall_birch_forest'                  /** 高大桦木森林 */         
    | 'tall_birch_hills'                   /** 高大桦木丘陵 */         
    | 'dark_forest_hills'                  /** 黑森林丘陵 */         
    | 'snowy_taiga_mountains'              /** 积雪的针叶林山地 */             
    | 'giant_spruce_taiga'                 /** 巨型云杉针叶林 */         
    | 'giant_spruce_taiga_hills'           /** 巨型云杉针叶林丘陵 */                 
    | 'modified_gravelly_mountains'        /** 沙砾山地 */                 
    | 'shattered_savanna'                  /** 破碎的热带草原 */         
    | 'shattered_savanna_plateau'          /** 破碎的热带高原 */                 
    | 'eroded_badlands'                    /** 被风蚀的恶地 */     
    | 'modified_wooded_badlands_plateau'   /** 繁茂的恶地高原变种 */                         
    | 'modified_badlands_plateau'          /** 恶地高原变种 */                 
    | 'bamboo_jungle'                      /** 竹林 */     
    | 'bamboo_jungle_hills'                /** 竹林丘陵 */         
    | 'soul_sand_valley'                   /** 灵魂沙峡谷 */         
    | 'crimson_forest'                     /** 绯红森林 */     
    | 'warped_forest'                      /** 诡异森林 */     
    | 'basalt_deltas'                      /** 玄武岩三角洲 */     